name = "personal-website"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-23"
preview_urls = true

compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22"

[env.production.vars]
NODE_VERSION = "22"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
