name = "personal-website"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-23"

compatibility_flags = ["nodejs_als"]

[vars]
NODE_VERSION = "22"

[env.production]
compatibility_date = "2023-01-22"

[env.production.vars]
NODE_VERSION = "22"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
